services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=subscription_manager
    depends_on:
      - db
    networks:
      - subscription-network

  db:
    image: mysql:8.0
    container_name: subscription-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: subscription_manager
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - subscription-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: subscription-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - subscription-network

volumes:
  db_data:

networks:
  subscription-network:
    driver: bridge